services:
  cmd:
    container_name: mechain-cmd
    image: "zkmelabs/mechain-cmd"
    networks:
      - mechain-network
    volumes:
      - "./deployment/dockerup/:/root/.mechain-cmd:Z"
    working_dir: "/root/.mechain-cmd"
    stdin_open: true
    tty: true
    command: /bin/bash

networks:
  mechain-network:
    external: true
